services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=vistula'
      - 'POSTGRES_PASSWORD=7878'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
